module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🧩', '🍉', '💜', '🌸', '🪴', '💊', '💫', '🍂', '🌟', '🎋', '😶‍🌫️', '🫀', '🧿', '👀', '😘', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💗'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/LufOYxXwmAKIRfrUVfmMQ1',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://files.catbox.moe/nld69x.jpg',
    NEWSLETTER_JID: '12036374@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: 'Gaga XMD',
    OWNER_NAME: 'Lil Gaga',
    OWNER_NUMBER: '263716857999',
    BOT_VERSION: '1.0.0',
    BOT_FOOTER: '> © Made with ❤️ by Lil Gaga',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029Vb6njtcG3R3n7HS5Vs0P',
};
